### ISSUE TITLE
Create a 2017 version of the website

### ISSUE THREAD

**Issue by samvloeberghs** [ng-be/2016-www-ng-be-org#101]
- [x] push current website to a 2016 specific repo
- [x] create new repo for 2017 website
- [x] make a small placeholder / teaser for the 2017 website
- [x] setup build system & repo
- [x] ...

**Comment by SamVerschueren** [comment]
Create a 2016 branch with the current website and push the changes for 2017 to master?

**Comment by samvloeberghs** [comment]
I guess we want an angular v4 website next time with server side rendering support for SEO :) So I would push this a seperate repo.. and rename it 2016 explicitly

**Comment by jvandemo** [comment]
I think it will be Angular 5 by then :-)

> I guess we want an angular v4 website next time with server side rendering support for SEO :) So I would push this a seperate repo.. and rename it 2016 explicitly

**Comment by samvloeberghs** [comment]
hahaha true!
