### ISSUE TITLE
Button hover states

### ISSUE THREAD

**Issue by SamVerschueren** [ng-be/2016-www-ng-be-org#4]
Site looks really slick! Congrats for that.

When navigating the website, I noticed different hover states for different buttons. Some buttons even don't have a hover state.

| normal | hover |
| --- | --- |
| <img width="138" alt="screen shot 2016-06-23 at 19 26 05" src="https://cloud.githubusercontent.com/assets/1913805/16313233/9d52d4b0-3978-11e6-9f34-4ce8380bd830.png"> | <img width="142" alt="screen shot 2016-06-23 at 19 26 12" src="https://cloud.githubusercontent.com/assets/1913805/16313242/a4929e0e-3978-11e6-8382-3c4932297610.png"> |
| <img width="233" alt="screen shot 2016-06-23 at 19 29 00" src="https://cloud.githubusercontent.com/assets/1913805/16313268/c3af927e-3978-11e6-97ee-7d961554e49f.png"> | <img width="233" alt="screen shot 2016-06-23 at 19 29 00" src="https://cloud.githubusercontent.com/assets/1913805/16313274/c89fce66-3978-11e6-88ac-a89aa9a9d938.png"> |
| <img width="105" alt="screen shot 2016-06-23 at 19 29 42" src="https://cloud.githubusercontent.com/assets/1913805/16313291/dc03d934-3978-11e6-8531-cb682889b446.png"> | <img width="106" alt="screen shot 2016-06-23 at 19 29 48" src="https://cloud.githubusercontent.com/assets/1913805/16313296/e42de51e-3978-11e6-8cd1-404320a19ea3.png"> |

wdyt?

**Comment by jvandemo** [comment]
@SamVerschueren &mdash; Agree, consistency would be better.

Which version do you prefer? /cc @samvloeberghs

**Comment by samvloeberghs** [comment]
@jvandemo well it should definitely have a consistent hover state.
I'll see if I can do a PR today! 

thx for reporting @SamVerschueren

**Comment by samvloeberghs** [comment]
fix: https://github.com/ng-be/www-ng-be-org/pull/6
@jvandemo you merge and close?

**Comment by jvandemo** [comment]
Fixed by #6. Thank you @SamVerschueren and @samvloeberghs!
