### ISSUE TITLE
Header alignment on smaller windows

### ISSUE THREAD

**Issue by SamVerschueren** [ng-be/2016-www-ng-be-org#5]
I'm not a designer, but it might look nicer if the 3 rows (logo, menu, button) are all aligned the same.

<img width="910" alt="screen shot 2016-06-23 at 19 34 49" src="https://cloud.githubusercontent.com/assets/1913805/16313534/ea2abe50-3979-11e6-8bf6-341a7896e9b8.png">

**Comment by samvloeberghs** [comment]
True that! We might need to add an item soon, so it will definitely be needed.. feel free to do PR :)

**Comment by jvandemo** [comment]
@SamVerschueren &mdash; Thanks, you are right, I will fix this asap.

**Comment by jvandemo** [comment]
Fix has been deployed 👍 

Thank you for notifying!

**Comment by SamVerschueren** [comment]
Yay, great job!

**Comment by jvandemo** [comment]
@SamVerschueren &mdash; Thanks for reporting Sam! 👍
