### ISSUE TITLE
implement jobboard on the homepage!

### ISSUE THREAD

**Issue by samvloeberghs** [ng-be/2016-www-ng-be-org#66]
A jobboard should be implemented on the homepage.
The jobboard should contain:
- company logo
- job title
- short job description
- to be put beneath organisers

&  link to job description entry on 3th party website

- [x] design entry
- [ ] put include on every page of the website 
- [ ] link to job descriptions on 3th party website

**Comment by SamVerschueren** [comment]
Jobs from sponsors you mean?

**Comment by samvloeberghs** [comment]
@SamVerschueren indeed! Let's hardcode them for now.. we'll share the doc soon

**Comment by SamVerschueren** [comment]
Assign it to me. Will do it when I have the document.

**Comment by samvloeberghs** [comment]
@SamVerschueren check slack for the doc

**Comment by SamVerschueren** [comment]
Should it open a new page with the full description when clicked?

**Comment by samvloeberghs** [comment]
No just an overview, with a short description and a link to the 3th party website

**Comment by SamVerschueren** [comment]
I linked to the job description of [ARHS Digital](https://www.arhs-group.com/jobs#GREX1AVMBYAN9) but not to the one of `Real Dolmen`. They added a request for multiple positions (Java, .NET, AngularJS, ...). So linking to `http://jobs.realdolmen.com` seems the best we can do.
