### ISSUE TITLE
the website needs to reflect the sold out state

### ISSUE THREAD

**Issue by samvloeberghs** [ng-be/2016-www-ng-be-org#67]
We should add a badge / warning somewhere that indicates that we are sold out :) jeeeeuj

- [x] use "fork me" style of design for badge/ribbon
- [x] add badge of soldout on the website

**Comment by SamVerschueren** [comment]
Maybe a ribbon in the upper right corner? Not really a designer, just suggesting :).

![68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67](https://cloud.githubusercontent.com/assets/1913805/20152082/145356be-a6bd-11e6-8412-06b59e541ced.png)

**Comment by samvloeberghs** [comment]
LGTM!

**Comment by SamVerschueren** [comment]
@samvloeberghs What do you mean with the badge? PR 73 adds the ribbon, anything else that needs to be shown?

**Comment by TYsewyn** [comment]
We can maybe disable the buttons, change the text to "Sold out!" and remove the links to ti.to?
Or maybe we can just remove the buttons completely?

**Comment by samvloeberghs** [comment]
People can still waitlist, so wouldn't remove them till after conf..

**Comment by SamVerschueren** [comment]
Change the button text from `Buy tickets` to `Waitlist` maybe?
