### ISSUE TITLE
update the links to sponsors etc

### ISSUE THREAD

**Issue by samvloeberghs** [ng-be/2016-www-ng-be-org#86]
@SamVerschueren When checking the schedule I saw a small "error":
The links to the speakers in the planning are linking without the full url:
https://ng-be.org/#philippe-deryck

It should be:
https://ng-be.org/conference-day#philippe-deryck

As an example see the quick links to the speakers on top of the page.

**Comment by SamVerschueren** [comment]
Strange. Shouldn't that work? If you pass an id to an `a` tag, shouldn't it just append it to the current URL of the same page.

Take this one for example: https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

If you look at the Table of Contents and you inspect the links, you will see `<a href="#overview">Overview</a>`, not the full url.

**Comment by SamVerschueren** [comment]
It looks like it's caused by the `base href` tag in the `head`. If you remove that, it works. But that might cause side effects.

**Comment by samvloeberghs** [comment]
We need to keep the base href, best to use the implementation mentioned at
the quick link of the speakers

**Comment by SamVerschueren** [comment]
Ah, didn't saw that one. On it!
