### ISSUE TITLE
add a link to the application on conf day

### ISSUE THREAD

**Issue by samvloeberghs** [ng-be/2016-www-ng-be-org#94]
- [ ] simple link / button to add on the website
- [ ] link to the application http://app.ng-be.org

**Comment by SamVerschueren** [comment]
Any ideas as to where we should add it? Like a horizontal bar between these two?

<img width="1288" alt="screen shot 2016-12-02 at 08 02 29" src="https://cloud.githubusercontent.com/assets/1913805/20825638/c7f5cf3a-b865-11e6-80bf-48c54f0ff236.png">

Or something more subtle? Want to add it but I'm not a good designer so asking for input here :).

**Comment by SamVerschueren** [comment]
Should this only appear on mobile, or also on desktop?

**Comment by samvloeberghs** [comment]
It's also usable on desktop, so the link should be available anywhere!

**Comment by SamVerschueren** [comment]
Alright, will do a PR today so we can evaluate the "design".

**Comment by SamVerschueren** [comment]
This is what I had in mind at first.

<img width="1186" alt="screen shot 2016-12-06 at 19 57 33" src="https://cloud.githubusercontent.com/assets/1913805/20939239/45c53cd0-bbee-11e6-9b0d-f45c3555b9b6.png">

Not sure about it. It looks ok on mobile.

<img width="332" alt="screen shot 2016-12-06 at 19 58 02" src="https://cloud.githubusercontent.com/assets/1913805/20939251/557d8c90-bbee-11e6-9d03-dbd8bd1faf69.png">

I could just add a new  link in the navigation bar as well with the text `APP` or something.

Feedback?

**Comment by samvloeberghs** [comment]
I would just mention "open mobile application" or something, is fine by me for the rest :)
